[toolchain]

[features]
resolution = true
skip-lint = false

[programs.devnet]
simple-oracle-quest = "9tSP8kXEUif9doAPhAbUKZm3qKNphpcHGKc35jLr1xEA"
# zk_oracle_quest = "B6qG7jPjiTcdnNS1Rttf5We5H4GbyN3dUqu8VKMFv5Eh"

[programs.localnet]
simple-oracle-quest = "9tSP8kXEUif9doAPhAbUKZm3qKNphpcHGKc35jLr1xEA"
# zk_oracle_quest = "B6qG7jPjiTcdnNS1Rttf5We5H4GbyN3dUqu8VKMFv5Eh"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/devnet-wallet.json"

[workspace]
members = ["programs/simple-oracle-quest"]
exclude = ["programs/zk-oracle-quest"]
